export const constants = {
  controls: {
    CONTROLS_CHANGE: "CONTROLS_CHANGE",
  },
  content: {
    CONTENT_LOADING_SUCCESS: "CONTENT_LOADING_SUCCESS",
    CONTENT_LOADING_FAILURE: "CONTENT_LOADING_FAILURE",
    CONTENT_FETCHING: "CONTENT_FETCHING",
    PAGINATE_CONTANT_SUCCESS: "PAGINATE_CONTANT_SUCCESS",
    PAGINATE_CONTENT_FAILURE: "PAGINATE_CONTENT_FAILURE",
    PAGINATE_PROCESS: "PAGINATE_PROCESS",
  },
  book: {
    BOOK_LOADING_SUCCESS: "BOOK_LOADING_SUCCESS",
    BOOK_LOADING_FAILURE: "BOOK_LOADING_FAILURE",
    BOOK_FETCHING: "BOOK_FETCHING",
  },
};
